from app.prompts.general import (
    SYSTEM_CONTEXT_PROMPT,
    SYSTEM_NO_CONTEXT_PROMPT,
    GENERAL_CHAT_PROMPT,
    RAG_FALLBACK_PROMPT,
)
from app.prompts.rag import (
    RAG_STAFF_PROMPT,
)
from app.prompts.web import (
    WEB_SEARCH_SYSTEM_PROMPT,
    WEB_SEARCH_DECISION_PROMPT,
)
from app.prompts.sql import (
    SQL_SYSTEM_PROMPT,
    SQL_QUERY_TEMPLATE,
)
from app.prompts.filesystem import (
    FILESYSTEM_SYSTEM_PROMPT_TEMPLATE,
)

__all__ = [
    "SYSTEM_CONTEXT_PROMPT",
    "SYSTEM_NO_CONTEXT_PROMPT",
    "GENERAL_CHAT_PROMPT",
    "RAG_FALLBACK_PROMPT",
    "RAG_STAFF_PROMPT",
    "WEB_SEARCH_SYSTEM_PROMPT",
    "WEB_SEARCH_DECISION_PROMPT",
    "SQL_SYSTEM_PROMPT",
    "SQL_QUERY_TEMPLATE",
    "FILESYSTEM_SYSTEM_PROMPT_TEMPLATE",
]
